#!/usr/bin/env bash
# install nginx on web-01 server
# Nginx should listen on port 80
#When querying Nginx at its root / with a GET request (requesting a page)
#using curl, it must return a page that contains the string Hello World!

sudo apt update -y
sudo apt install nginx -y
sudo service start
sudo ufw allow 'HTTP'
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx restart
