#!/usr/bin/env bash
# install nginx on web-01 server
# Nginx should listen on port 80
#When querying Nginx at its root / with a GET request (requesting a page)
#using curl, it must return a page that contains the string Hello World!
#redirect /redirect_me to another page permanently

#update all package repositories
sudo apt update -y

# install nginx and start it
sudo apt install nginx -y

# firewall setting: allow nginx to serve on port 80
sudo ufw allow 'Nginx HTTP'

# replace the content of the served page
echo "Hello World!" | sudo tee /var/www/html/index.html


# grant user ownership of the web files

sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www


# redirect /redirect_me to youtube video
sudo sed -i '38i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
