#!/usr/bin/env bash
#script to link the default file in sites-enabled to the default file in sites-available

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
