#!/usr/bin/env bash
# A script that creates a file and traps signals

pid=$(pgrep -f "bash ./100-process_and_pid_file")

echo "$pid" > /var/run/myscript.pid

killfunc() {
	rm /var/run/myscript.pid
	exit

}

while true
do

	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && killfunc' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
	trap 'killfunc' SIGQUIT
done
