#!/usr/bin/env bash
# This script implements if, elif and else statements

i=1
while (( i < 11 )); do
	if [[ $i == 4 ]]
	then
		echo "bad luck"
	elif [[ $i == 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done

