#!/usr/bin/env bash
# A bash script that gives information about a file

FILE=school
if [[ -e $FILE ]];then
	echo "school file exists"
	if [[ -s $FILE ]]; then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
	if [[ -f $FILE ]];then
		echo "$FILE is a regular file"
	fi
else
	echo "$FILE file does not exist"
fi
