#!/usr/bin/env bash
#script to configure nginx to run as another user
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/80/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache
sudo -u nginx service nginx start
