#!/usr/bin/env bash
#script to configure nginx to run as another user
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache
sudo -u nginx service nginx start
