#!/usr/bin/env bash
# script to configure nginx as another user
pkill apache
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod +x /etc/nginx/nginx.conf
sudo -u nginx service nginx start
