#!/usr/bin/env bash
#  a Bash script that uses ssh to connect to your
# server using the private key ~/.ssh/school with the user ubuntu.
cat ~/.ssh/school | ssh ubuntu@100.24.236.208 "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"

ssh ubuntu@100.24.236.208
